# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # The HTTP/S ports are now handled by the nginx-proxy service
      - "80:80/tcp"
      # - "443:443/tcp"    <-- REMOVE
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      FTLCONF_dns_upstreams: "1.1.1.1;1.0.0.1"
      TZ: "Asia/Kuala_Lumpur"
      FTLCONF_webserver_api_password: ${ADMIN_PASSWORD}
      FTLCONF_dns_listeningMode: "all"
    volumes:
      - "/etc/pihole:/etc/pihole"
    cap_add:
      - SYS_NICE
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    # Ports are no longer needed here, they are handled by the nginx-proxy
    # ports:
    #   - 9443:9443      <-- REMOVE
    #   - 8000:8000      <-- REMOVE

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    restart: unless-stopped
    ports:
      # The single entry point for all web traffic
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - pihole
      - portainer
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  portainer_data:
    name: portainer_data

networks:
  default:
    name: portainer_network